db:
  image: mysql:5.6
  ports:
    - "3306:3306"
  volumes_from:
    - dbdata
  environment:
    - MYSQL_ROOT_PASSWORD=magento2
    - MYSQL_DATABASE=magento2
    - MYSQL_USER=magento2
    - MYSQL_PASSWORD=magento2

dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql

app:
  build: .
  ports:
    - "80:80"
  links:
    - db
  volumes:
    - ./data/.composer:/root/.composer
  environment:
    - MYSQL_DATABASE=magento2
    - MYSQL_USER=magento2
    - MYSQL_PASSWORD=magento2
    - MYSQL_HOST=db
    - MAGENTO_HOST=magento.local
    - MAGENTO_PATH=/opt/magento2
